global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: default

receivers:
  - name: default
    webhook_configs:
      - url: 'http://localhost:5001/'