events {}

http {
  upstream backend {
    server receiver:8000;
    server filter:8081;
    server storage: 8002;


    # least_conn;    - strategies
    # random;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend;
    }
  }
}